// These runtimes ship inside the download. They use an in-memory DuckDB database
// and explicit stable IDs; no Data Canvas server or JavaScript runtime is required.
export const pythonRuntime = `# Generated by Data Canvas. See README.txt and coverage.json before editing.
# Run: python analysis.py (paths resolve relative to this script).
from pathlib import Path
import json
import duckdb
import pandas as pd
import numpy as np

ROOT = Path(__file__).resolve().parent
con = duckdb.connect(":memory:")
con.execute("SET TimeZone='UTC'")
if not con.execute("SELECT version()").fetchone()[0].startswith("v1.5.4"):
    raise RuntimeError("Use DuckDB 1.5.4 for this Data Canvas export; see requirements.txt")

def read_json(path):
    return json.loads((ROOT / path).read_text(encoding="utf-8"))

def qi(name):
    return '"' + name.replace('"', '""') + '"'

def qs(value):
    return "'" + str(value).replace("'", "''") + "'"

def read_frame(name):
    # Keep row identity while null-aware pandas dtypes preserve three-valued logic.
    return con.execute("SELECT * EXCLUDE (__lineage) FROM " + qi(name)).df().convert_dtypes(convert_integer=False)

def as_condition(value, index):
    return pd.Series(value, index=index, dtype="boolean")

def as_number(value, index):
    return pd.Series(value, index=index, dtype="Float64")

def finite(value, index):
    result = as_number(value, index)
    return result.where(np.isfinite(result), pd.NA)

def save_frame(frame, name, input_name, projection):
    # Materialize immediately: later registrations must not change previous steps.
    native = frame.copy()
    native["__dc_order"] = range(len(native))
    con.register("__dc_native", native)
    fields = ([projection] if projection else []) + ['n."__rid"', 'i."__lineage"']
    con.execute("CREATE TABLE " + qi(name) + " AS SELECT " + ", ".join(fields)
                + ' FROM "__dc_native" n JOIN ' + qi(input_name)
                + ' i ON n."__rid" = i."__rid" ORDER BY n."__dc_order"')
    con.unregister("__dc_native")

def sql_step(path):
    con.execute((ROOT / path).read_text(encoding="utf-8"))

def export_outputs():
    destination = ROOT / "results"
    destination.mkdir(exist_ok=True)
    outputs = {}
    for output in read_json("outputs.json"):
        columns = output["columns"]
        frame = read_frame(output["table"])
        frame = frame.loc[:, [c["id"] for c in columns]].rename(columns={c["id"]: c["name"] for c in columns})
        outputs[output["id"]] = frame
        if columns:
            fields = ", ".join(qi(c["id"]) + " AS " + qi(c["name"]) for c in columns)
            query = "SELECT " + fields + " FROM " + qi(output["table"])
            con.execute("COPY (" + query + ") TO " + qs(destination / (output["id"] + ".csv")) + " (FORMAT CSV, HEADER)")
        else:
            # CSV cannot represent a zero-column table faithfully.
            (destination / (output["id"] + ".json")).write_text(json.dumps({"rows": len(frame), "columns": []}), encoding="utf-8")
    print("Exported", len(outputs), "tables to", destination)
    return outputs

# Typed source setup uses the exact saved import settings and full input assets.
for statement in read_json("sources.json"):
    con.execute(statement)
`;

export const rRuntime = `# Generated by Data Canvas. See README.txt and coverage.json before editing.
# Run: Rscript analysis.R. In RStudio, setwd() to the extracted folder first.
suppressPackageStartupMessages({
  library(DBI)
  library(duckdb)
  library(dplyr)
  library(dbplyr)
  library(jsonlite)
  library(tibble)
  library(bit64)
})
script_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
ROOT <- if (length(script_arg)) dirname(normalizePath(sub("^--file=", "", script_arg[[1]]))) else getwd()
Sys.setenv(TZ = "UTC")
con <- dbConnect(duckdb(), dbdir = ":memory:", bigint = "integer64")
# Sources contain already-parsed UTC TIMESTAMP values, avoiding platform-dependent
# source parsing or an ICU extension download. If ICU is bundled, fix its zone too.
icu <- dbGetQuery(con, "SELECT loaded FROM duckdb_extensions() WHERE extension_name = 'icu'")
if (nrow(icu) && isTRUE(icu$loaded[[1]])) dbExecute(con, "SET TimeZone='UTC'")
if (!startsWith(dbGetQuery(con, "SELECT version() AS version")$version[[1]], "v1.5.4")) {
  stop("Use DuckDB 1.5.4 for this Data Canvas export; see README.txt")
}

read_json <- function(path) fromJSON(file.path(ROOT, path), simplifyVector = FALSE)
qi <- function(name) as.character(dbQuoteIdentifier(con, name))
qs <- function(value) as.character(dbQuoteString(con, value))

save_table <- function(data, name) {
  # Tidyverse verbs remain lazy in DuckDB, preserving int64 and timestamp precision.
  dbExecute(con, paste0("CREATE TABLE ", qi(name), " AS ", as.character(sql_render(data))))
  invisible(NULL)
}

sql_step <- function(path) {
  dbExecute(con, paste(readLines(file.path(ROOT, path), warn = FALSE, encoding = "UTF-8"), collapse = "\\n"))
  invisible(NULL)
}

export_outputs <- function() {
  destination <- file.path(ROOT, "results")
  dir.create(destination, showWarnings = FALSE)
  outputs <- list()
  for (output in read_json("outputs.json")) {
    columns <- output$columns
    ids <- vapply(columns, function(x) x$id, character(1))
    labels <- vapply(columns, function(x) x$name, character(1))
    if (length(columns)) {
      # R's integer64 reserves -2^63 for NA. Preserve the complete int64 range
      # by returning affected columns as decimal strings, with an explicit notice.
      collect_fields <- vapply(columns, function(x) {
        field <- qi(x$id)
        if (identical(x$type, "integer")) {
          query <- paste0("SELECT count(*) > 0 AS present FROM ", qi(output$table), " WHERE ", field, " = CAST('-9223372036854775808' AS BIGINT)")
          if (isTRUE(dbGetQuery(con, query)$present[[1]])) {
            message(output$name, " / ", x$name, ": returned as character to preserve the minimum int64 value")
            field <- paste0("CAST(", field, " AS VARCHAR)")
          }
        }
        paste(field, "AS", qi(x$id))
      }, character(1))
      frame <- as_tibble(dbGetQuery(con, paste("SELECT", paste(collect_fields, collapse = ", "), "FROM", qi(output$table))))
      names(frame) <- labels
      fields <- paste(vapply(columns, function(x) paste(qi(x$id), "AS", qi(x$name)), character(1)), collapse = ", ")
      query <- paste("SELECT", fields, "FROM", qi(output$table))
      dbExecute(con, paste0("COPY (", query, ") TO ", qs(file.path(destination, paste0(output$id, ".csv"))), " (FORMAT CSV, HEADER)"))
    } else {
      n <- as.integer(dbGetQuery(con, paste("SELECT count(*) AS n FROM", qi(output$table)))$n[[1]])
      frame <- new_tibble(list(), nrow = n)
      write_json(list(rows = n, columns = list()), file.path(destination, paste0(output$id, ".json")), auto_unbox = TRUE)
    }
    outputs[[output$id]] <- frame
  }
  message("Exported ", length(outputs), " tables to ", destination)
  outputs
}

# Typed source setup uses the exact saved import settings and full input assets.
for (statement in read_json("sources.json")) dbExecute(con, statement)
`;
